version: "3"

services:
  db:
    image: postgres:14.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: coinwatch
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    expose:
      - 5432
    ports:
      - 5432:5432

  backend:
    build: server
    container_name: backend
    depends_on:
      - db
    expose:
      - 8080
    ports:
      - 8080:8080

  frontend:
    build: frontend
    container_name: frontend
    expose:
      - 3000