version: "3"

services:
  postgres:
    image: postgres:14.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: crypto_portfolio_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    expose:
      - 5432
    ports:
      - 5432:5432

networks:
  postgres:
    driver: bridge

volumes:
  postgres: